name: Build
on:
  workflow_call:
    inputs:
      version_format:
        description: "Versioning format"
        required: false
        type: string
        default: "v${major}.${minor}.${patch}"
      attest:
        description: "Generate attestations"
        required: false
        type: boolean
        default: true
  # checkov:skip=CKV_GHA_7
  workflow_dispatch:
    inputs:
      version_format:
        description: "Versioning format"
        required: false
        type: string
        default: "v${major}.${minor}.${patch}"
      attest:
        description: "Generate attestations"
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    runs-on: windows-latest
    env:
      BUILD_OUTPUT: "__main__.dist"
      Executable: RimSort.exe
      platform: "Windows"
      arch: "x86_64"

    steps:
      - name: Check-out repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Add submodules to pythonpath
        id: pythonpath
        run: |
          echo "PYTHONPATH=$PYTHONPATH;${{ github.workspace }}\submodules\SteamworksPy" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Get semantic version
        id: sem_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          version_format: "${{ inputs.version_format }}"
          change_path: "app libs submodules themes"

      - name: Make (overwrite) version.xml
        id: version_xml
        run: |
          rm -f version.xml
          {
          echo "<version>"
          echo "  <version>${{ steps.sem_version.outputs.version  }}</version>"
          echo "  <major>${{ steps.sem_version.outputs.major }}</major>"
          echo "  <minor>${{ steps.sem_version.outputs.minor }}</minor>"
          echo "  <patch>${{ steps.sem_version.outputs.patch }}</patch>"
          echo "  <increment>${{ steps.sem_version.outputs.increment }}</increment>"
          echo "  <commit>${{ steps.sem_version.outputs.current_commit   }}</commit>"
          echo "  <tag>${{ steps.sem_version.outputs.version_tag  }}</tag>"
          echo "</version>"
          } >> version.xml
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          activate-environment: true

      - name: Install Dependencies
        shell: bash
        run: uv sync --locked --no-dev --group build

      - name: Build Actions
        shell: bash
        run: |
          set -e
          uv run --frozen python \
          ./distribute.py \
          --product-version='${{ steps.sem_version.outputs.major }}.
            ${{ steps.sem_version.outputs.minor }}.
            ${{ steps.sem_version.outputs.patch }}.
            ${{ steps.sem_version.outputs.increment }}' \
          --skip-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app/__main__.py
          mode: standalone
          static-libpython: auto
          product-version: >-
            ${{ steps.sem_version.outputs.major }}.
            ${{ steps.sem_version.outputs.minor }}.
            ${{ steps.sem_version.outputs.patch }}.
            ${{ steps.sem_version.outputs.increment }}
          file-description: "RimSort"
          include-data-files: |
            version.xml=version.xml
          nofollow-import-to: "sqlalchemy.dialects.oracle"
        env:
          PYTHONPATH: ${{ steps.pythonpath.outputs.PYTHONPATH }}

      - name: Set FILENAME
        id: filename
        run: |
          FILENAME="Windows_x86_64"
          echo "FILENAME=$FILENAME" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Find Executable
        id: find_executable
        run: |
          executable=$(find . -name "RimSort.exe" | head -n 1)
          echo "EXECUTABLE=$executable" >> "$GITHUB_OUTPUT"
          echo "Executable found at $executable"
        shell: bash

      - name: Create MSI Package
        if: matrix.platform == 'Windows'
        run: |
          dotnet tool install --global wix --version 6.0.0
          
          # Generate EULA.rtf from LICENSE.md for WiX License dialog
          New-Item -ItemType Directory -Force -Path "themes\windows" | Out-Null
          choco install pandoc -y
          pandoc -s -o "themes\windows\EULA.rtf" "LICENSE.md"
          
          wix extension add WixToolset.UI.wixext
          
          wix build data\RimSort.wxs `
            -ext WixToolset.UI.wixext `
            -d PackageVersion="${{ steps.sem_version.outputs.major }}.${{ steps.sem_version.outputs.minor }}.${{ steps.sem_version.outputs.patch }}.${{ steps.sem_version.outputs.increment }}" `
            -d License="themes\windows\EULA.rtf" `
            -o "RimSort-${{ steps.sem_version.outputs.version }}-${{ matrix.platform }}-${{ matrix.arch }}.msi"
        shell: powershell

      - name: Generate executable attestations
        uses: actions/attest-build-provenance@v2.4.0
        if: ${{ inputs.attest }}
        with:
          subject-path: ${{ steps.find_executable.outputs.EXECUTABLE }}

      - name: Generate MSI attestation
        uses: actions/attest-build-provenance@v2.4.0
        if: ${{ inputs.attest }}
        with:
          subject-path: ./RimSort-${{ steps.sem_version.outputs.version }}-Windows-x86_64.msi

      - name: Rename new build
        run: |
          cd build
          mv "__main__.dist" "output"
          tar -cvf "Windows_x86_64.tar" "output" 
          rm -rf "output"
        shell: bash

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2.4.0
        if: ${{ inputs.attest }}
        with:
          subject-path: ./build/Windows_x86_64.tar

      - name: Upload folder as artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows_x86_64
          path: ./build/Windows_x86_64.tar
          if-no-files-found: error

      - name: Upload MSI Package
        uses: actions/upload-artifact@main
        with:
          name: Windows_x86_64_msi
          path: ./RimSort-${{ steps.sem_version.outputs.version }}-Windows-x86_64.msi
          if-no-files-found: error

    outputs:
      filename: Windows_x86_64

  post-build-test:
    needs: build
    uses: ./.github/workflows/test_builds.yml
