name: Build
on:
  workflow_call:
    inputs:
      version_format:
        description: "Versioning format"
        required: false
        type: string
        default: "v${major}.${minor}.${patch}"
      attest:
        description: "Generate attestations"
        required: false
        type: boolean
        default: true
  # checkov:skip=CKV_GHA_7
  workflow_dispatch:
    inputs:
      version_format:
        description: "Versioning format"
        required: false
        type: string
        default: "v${major}.${minor}.${patch}"
      attest:
        description: "Generate attestations"
        required: false
        type: boolean
        default: true

permissions: {}

jobs:
  build:
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write

    runs-on: windows-latest
    env:
      BUILD_OUTPUT: "__main__.dist"
      Executable: RimSort.exe
      platform: "Windows"
      arch: "x86_64"

    steps:
      - name: Check-out repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Add submodules to pythonpath
        id: pythonpath
        run: |
          echo "PYTHONPATH=$PYTHONPATH;${{ github.workspace }}\submodules\SteamworksPy" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Get semantic version
        id: sem_version
        uses: PaulHatch/semantic-version@v5.4.0
        with:
          version_format: "${{ inputs.version_format }}"
          change_path: "app libs submodules themes"

      - name: Make (overwrite) version.xml
        id: version_xml
        run: |
          rm -f version.xml
          {
          echo "<version>"
          echo "  <version>${{ steps.sem_version.outputs.version  }}</version>"
          echo "  <major>${{ steps.sem_version.outputs.major }}</major>"
          echo "  <minor>${{ steps.sem_version.outputs.minor }}</minor>"
          echo "  <patch>${{ steps.sem_version.outputs.patch }}</patch>"
          echo "  <increment>${{ steps.sem_version.outputs.increment }}</increment>"
          echo "  <commit>${{ steps.sem_version.outputs.current_commit   }}</commit>"
          echo "  <tag>${{ steps.sem_version.outputs.version_tag  }}</tag>"
          echo "</version>"
          } >> version.xml
        shell: bash

      - name: Setup Python
        uses: actions/setup-python@main
        with:
          python-version: "3.12"
          architecture: "x64"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: pip install -r requirements.txt -r requirements_build.txt

      - name: Build Actions
        shell: bash
        run: |
          set -e
          python distribute.py \
          --skip-pip \
          --product-version='${{ steps.sem_version.outputs.major }}.
            ${{ steps.sem_version.outputs.minor }}.
            ${{ steps.sem_version.outputs.patch }}.
            ${{ steps.sem_version.outputs.increment }}' \
          --skip-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: app/__main__.py
          mode: standalone
          static-libpython: auto
          product-version: >-
            ${{ steps.sem_version.outputs.major }}.
            ${{ steps.sem_version.outputs.minor }}.
            ${{ steps.sem_version.outputs.patch }}.
            ${{ steps.sem_version.outputs.increment }}
          file-description: "RimSort"
          include-data-files: |
            version.xml=version.xml
        env:
          PYTHONPATH: ${{ steps.pythonpath.outputs.PYTHONPATH }}

      - name: Set FILENAME
        id: filename
        run: |
          FILENAME="Windows_x86_64"
          echo "FILENAME=$FILENAME" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Find Executable
        id: find_executable
        run: |
          executable=$(find . -name "RimSort.exe" | head -n 1)
          echo "EXECUTABLE=$executable" >> "$GITHUB_OUTPUT"
          echo "Executable found at $executable"
        shell: bash

      - name: Create MSI Package
        run: |
          choco install wixtoolset -y
          
          $env:PATH += ";C:\Program Files (x86)\WiX Toolset v3.11\bin"

          heat.exe dir "build\\__main__.dist" -cg MainDist -dr INSTALLFOLDER -gg -sfrag -sreg -srd -var var.DistDir -out maindist.wxs

          $wixContent = @"
          <?xml version="1.0" encoding="UTF-8"?>
          <Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
            <Product Id="*" 
                     Name="RimSort" 
                     Language="1033" 
                     Version="${{ steps.sem_version.outputs.major }}.${{ steps.sem_version.outputs.minor }}.${{ steps.sem_version.outputs.patch }}.${{ steps.sem_version.outputs.increment }}" 
                     Manufacturer="RimSort Team" 
                     UpgradeCode="d4f7c3b9-8a5e-4e52-bb9f-3c2d1f7a9e24">
              <Package InstallerVersion="400" Compressed="yes" InstallScope="perMachine" />
              <MajorUpgrade DowngradeErrorMessage="A newer version of [ProductName] is already installed." />
              <MediaTemplate EmbedCab="yes" />

              <Property Id="DistDir" Value="build\\__main__.dist" />

              <Property Id="INSTALLFOLDER">
                <RegistrySearch Id="PreviousInstallDirSearch" Root="HKCU" Key="Software\RimSort" Name="InstallDir" Type="raw" />
              </Property>

              <CustomAction Id="SetDefaultInstallDir" Script="vbscript" Execute="immediate">
                <![CDATA[
                  Dim fso, installDir
                  Set fso = CreateObject("Scripting.FileSystemObject")
                  
                  installDir = Session.Property("INSTALLFOLDER")
                  
                  If installDir = "" Then
                    If fso.DriveExists("D:\") Then
                      installDir = "D:\Program Files\RimSort"
                    Else
                      installDir = "C:\Program Files\RimSort"
                    End If
                    Session.Property("INSTALLFOLDER") = installDir
                  End If
                ]]>
              </CustomAction>

              <Icon Id="RimSortIcon" SourceFile="themes\\default-icons\\AppIcon.ico" />

              <Directory Id="TARGETDIR" Name="SourceDir">
                <Directory Id="ProgramFilesFolder">
                  <Directory Id="INSTALLFOLDER" Name="RimSort" />
                </Directory>
                <Directory Id="ProgramMenuFolder">
                  <Directory Id="ApplicationProgramsFolder" Name="RimSort"/>
                </Directory>
              </Directory>

              <Feature Id="ProductFeature" Title="RimSort" Level="1">
                <ComponentGroupRef Id="MainDist" />
                <ComponentGroupRef Id="ShortcutComponents" />
                <ComponentGroupRef Id="RegistryComponents" />
              </Feature>

              <UIRef Id="WixUI_InstallDir" />

              <Property Id="WIXUI_INSTALLDIR" Value="INSTALLFOLDER" />

              <InstallExecuteSequence>
                <Custom Action="SetDefaultInstallDir" After="ValidateProductID">NOT Installed</Custom>
              </InstallExecuteSequence>

              <InstallUISequence>
                <Custom Action="SetDefaultInstallDir" After="ValidateProductID">NOT Installed</Custom>
              </InstallUISequence>

              <ComponentGroup Id="ShortcutComponents" Directory="ApplicationProgramsFolder">
                <Component Id="StartMenuShortcut" Guid="3C5F5459-99AE-5A3E-0422-E64DA66B4443">
                  <RegistryValue Root="HKCU"
                                Key="Software\RimSort"
                                Name="StartMenuShortcutInstalled"
                                Type="integer"
                                Value="1"
                                KeyPath="yes" />
                  <Shortcut Id="ApplicationStartMenuShortcut"
                            Directory="ApplicationProgramsFolder"
                            Name="RimSort"
                            Target="[INSTALLFOLDER]RimSort.exe"
                            WorkingDirectory="INSTALLFOLDER"
                            Icon="RimSortIcon"
                            IconIndex="0"
                            Advertise="no" />
                  <RemoveFolder Id="RemoveApplicationProgramsFolder"
                                Directory="ApplicationProgramsFolder"
                                On="uninstall" />
                </Component>
              </ComponentGroup>

              <ComponentGroup Id="RegistryComponents" Directory="INSTALLFOLDER">
                <Component Id="InstallFlagRegistry" Guid="92D579F1-DC10-4E2F-87F5-25B36476C271">
                  <RegistryValue Root="HKCU"
                                Key="Software\RimSort\StartMenu"
                                Name="installed"
                                Type="integer"
                                Value="1"
                                KeyPath="yes" />
                </Component>
                <Component Id="InstallPathRegistry" Guid="A1B2C3D4-E5F6-7890-ABCD-EF1234567890">
                  <RegistryValue Root="HKCU"
                                Key="Software\RimSort"
                                Name="InstallDir"
                                Type="string"
                                Value="[INSTALLFOLDER]"
                                KeyPath="yes" />
                </Component>
              </ComponentGroup>
            </Product>
          </Wix>
          "@
          $wixContent | Out-File -FilePath "RimSort.wxs" -Encoding UTF8

          candle.exe `
            -dDistDir="build\\__main__.dist" `
            maindist.wxs RimSort.wxs

          light.exe `
            -ext WixUIExtension `
            -cultures:en-us `
            maindist.wixobj RimSort.wixobj `
            -o "RimSort-${{ steps.sem_version.outputs.version }}-Windows-x86_64.msi"
        shell: powershell

      - name: Generate executable attestations
        uses: actions/attest-build-provenance@v2.4.0
        if: ${{ inputs.attest }}
        with:
          subject-path: ${{ steps.find_executable.outputs.EXECUTABLE }}

      - name: Generate MSI attestation
        uses: actions/attest-build-provenance@v2.4.0
        if: ${{ inputs.attest }}
        with:
          subject-path: ./RimSort-${{ steps.sem_version.outputs.version }}-Windows-x86_64.msi

      - name: Rename new build
        run: |
          cd build
          mv "__main__.dist" "output"
          tar -cvf "Windows_x86_64.tar" "output" 
          rm -rf "output"
        shell: bash

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2.4.0
        if: ${{ inputs.attest }}
        with:
          subject-path: ./build/Windows_x86_64.tar

      - name: Upload folder as artifact
        uses: actions/upload-artifact@main
        with:
          name: Windows_x86_64
          path: ./build/Windows_x86_64.tar
          if-no-files-found: error

      - name: Upload MSI Package
        uses: actions/upload-artifact@main
        with:
          name: Windows_x86_64_msi
          path: ./RimSort-${{ steps.sem_version.outputs.version }}-Windows-x86_64.msi
          if-no-files-found: error

    outputs:
      filename: Windows_x86_64

  post-build-test:
    needs: build
    uses: ./.github/workflows/test_builds.yml